# Generated by Django 3.2.4 on 2021-06-10 06:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('s1_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 6, 10, 6, 35, 37, 964714, tzinfo=utc)),
        ),
    ]
