# Generated by Django 3.2.4 on 2021-06-10 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s1_app', '0002_student_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
    ]
