# Generated by Django 3.2.4 on 2021-06-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s1_app', '0003_remove_student_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_year',
            field=models.IntegerField(default=0),
        ),
    ]
