# Generated by Django 3.2.4 on 2021-06-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s1_app', '0004_student_birth_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
